# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.3.11
_src_path: https://github.com/wabenet/copier-dodo-plugin
archetype: other
archetype_other: plugin
components: []
description: Adds support for buildkit as a dodo builder plugin.
lifecycle: production
name: buildkit

